#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nmbapp
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        formate_sql: true